apiVersion: apps/v1
kind: Deployment 
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 5
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: arunagri03/boardgame
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
            
---
apiVersion: v1 
kind: Service 
metadata: 
  name: boardgame-ssvc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 8090
      targetPort: 8090
  type: LoadBalancer 
